spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itta?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: a570911275
    driver-class-name: com.mysql.cj.jdbc.Driver