server:
  port: 8080
spring:
  profiles: prod
  datasource:
    # 如果存在多个数据源，监控的时候可以通过名字来区分开来
    name: mysql
    # 连接数据库的url
    url: jdbc:mysql://119.3.213.219:3306/itta?characterEncoding=utf-8&serverTimezone=GMT%2B8
    # 连接数据库的账号
    username: huangyuyu
    # 连接数据库的密码
    password: Aa570911275123@
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver